build:
  environment:
    scala: "3.8.1"  # or latest 3.x version

dependencies:
  pre:
    - sbt update

tests:
  override:
    - sbt "scalafmtCheckAll"
#    - sbt coverage test
#    - coverage: 'target/scala-3.8.1/scoverage-report/scoverage.xml'

checks:
  scala:
    duplication: true
    style_violations: true  # Uses scalafmt reports

tools:
  # Scala 3 prefers scalafmt over scalastyle
  scalafmt:
    enabled: true