build:
  nodes:
    analysis:
      environment:
        java: "21.0.5"
      dependencies:
        override:
          - sbt "project pekko-processors-sagas" update
      tests:
        override:
          - command: sbt "project pekko-processors-sagas" "scalafmtCheckAll"
          - command: sbt "project pekko-processors-sagas" coverage test coverageReport
            coverage:
              file: 'pekko-processors-sagas/target/scala-3.8.1/scoverage-report/scoverage.xml'
              format: 'scoverage-xml'
