addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.2")
addSbtPlugin("com.github.sbt"    % "sbt-dynver"          % "5.1.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "2.3.1")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.10.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.10.4")
addSbtPlugin("com.thesamet"      % "sbt-protoc"          % "1.0.8")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.13.0")